version: 0.0
os: windows
phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm
  build:
    commands:
      - echo Building...
      - npm localBuild
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
  destination: c:\inetpub\wwwroot\fastdoMainSite
