version: 0.0
os: windows
files:
  - source: \public\index.html
    destination: c:\inetpub\wwwroot\fastdoMainSite
hooks:
  BeforeInstall:
    - location: \public\before-install.bat
      timeout: 900
