version: 0.0
os: windows

files:
  - source: \public\index.html
    destination: c:\inetpub\wwwroot\fastdoMainSite
hooks:
  BeforeInstall:
    - location: \public\scripts\before-install.bat
      timeout: 900
#files:
#  - source: \build
#   destination: c:\inetpub\wwwroot\fastdoMainSite
phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm i
  build:
    commands:
      - echo Building...
      - npm run localBuild

