/**User Reducer Types */
export const SET_AUTHENTICATED='SET_AUTHENTICATED'
export const SET_UNAUTHENTICATED='SET_UNAUTHENTICATED'
export const SET_USER='SET_USER'
export const LOADING_USER='LOADING_USER'
export const LOADING_ERROR='LOADING_ERROR'
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';
/**Ui Reducer Types */
export const SET_ERRORS='SET_ERRORS'
export const CLEAR_ERRORS='CLEAR_ERRORS'
export const LOADING_UI='LOADING_UI'
export const STOP_LOADING_UI='STOP_LOADING_UI'
/**Data Reducer Types */
export const LOADING_SEARCH_DATA='LOADING_SEARCH_DATA'
export const Stop_LOADING_SEARCH_DATA='Stop_LOADING_SEARCH_DATA'
export const SET_SEARCH_Q='SET_SEARCH_Q'
export const SET_SELECTED_CITIES='SET_SELECTED_CITIES'
export const SET_SELECTED_DESTICTS='SET_SELECTED_DESTICTS'
export const SET_SEARCH_TABLE_DATA='SET_SEARCH_TABLE_DATA'
export const SET_SEARCH_FILTERED_DATA='SET_SEARCH_FILTERED_DATA'